-- Table: public.Roles

-- DROP TABLE IF EXISTS public."Roles";

CREATE TABLE IF NOT EXISTS public."Roles"
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    type character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT "Roles_pkey" PRIMARY KEY (id),
    CONSTRAINT "Roles_name_key" UNIQUE (name),
    CONSTRAINT "Roles_name_key1" UNIQUE (name),
    CONSTRAINT "Roles_name_key10" UNIQUE (name),
    CONSTRAINT "Roles_name_key11" UNIQUE (name),
    CONSTRAINT "Roles_name_key12" UNIQUE (name),
    CONSTRAINT "Roles_name_key13" UNIQUE (name),
    CONSTRAINT "Roles_name_key14" UNIQUE (name),
    CONSTRAINT "Roles_name_key15" UNIQUE (name),
    CONSTRAINT "Roles_name_key16" UNIQUE (name),
    CONSTRAINT "Roles_name_key17" UNIQUE (name),
    CONSTRAINT "Roles_name_key18" UNIQUE (name),
    CONSTRAINT "Roles_name_key19" UNIQUE (name),
    CONSTRAINT "Roles_name_key2" UNIQUE (name),
    CONSTRAINT "Roles_name_key20" UNIQUE (name),
    CONSTRAINT "Roles_name_key21" UNIQUE (name),
    CONSTRAINT "Roles_name_key22" UNIQUE (name),
    CONSTRAINT "Roles_name_key23" UNIQUE (name),
    CONSTRAINT "Roles_name_key24" UNIQUE (name),
    CONSTRAINT "Roles_name_key25" UNIQUE (name),
    CONSTRAINT "Roles_name_key26" UNIQUE (name),
    CONSTRAINT "Roles_name_key27" UNIQUE (name),
    CONSTRAINT "Roles_name_key28" UNIQUE (name),
    CONSTRAINT "Roles_name_key29" UNIQUE (name),
    CONSTRAINT "Roles_name_key3" UNIQUE (name),
    CONSTRAINT "Roles_name_key30" UNIQUE (name),
    CONSTRAINT "Roles_name_key31" UNIQUE (name),
    CONSTRAINT "Roles_name_key32" UNIQUE (name),
    CONSTRAINT "Roles_name_key33" UNIQUE (name),
    CONSTRAINT "Roles_name_key34" UNIQUE (name),
    CONSTRAINT "Roles_name_key35" UNIQUE (name),
    CONSTRAINT "Roles_name_key36" UNIQUE (name),
    CONSTRAINT "Roles_name_key37" UNIQUE (name),
    CONSTRAINT "Roles_name_key38" UNIQUE (name),
    CONSTRAINT "Roles_name_key39" UNIQUE (name),
    CONSTRAINT "Roles_name_key4" UNIQUE (name),
    CONSTRAINT "Roles_name_key40" UNIQUE (name),
    CONSTRAINT "Roles_name_key41" UNIQUE (name),
    CONSTRAINT "Roles_name_key42" UNIQUE (name),
    CONSTRAINT "Roles_name_key43" UNIQUE (name),
    CONSTRAINT "Roles_name_key44" UNIQUE (name),
    CONSTRAINT "Roles_name_key45" UNIQUE (name),
    CONSTRAINT "Roles_name_key46" UNIQUE (name),
    CONSTRAINT "Roles_name_key47" UNIQUE (name),
    CONSTRAINT "Roles_name_key48" UNIQUE (name),
    CONSTRAINT "Roles_name_key49" UNIQUE (name),
    CONSTRAINT "Roles_name_key5" UNIQUE (name),
    CONSTRAINT "Roles_name_key50" UNIQUE (name),
    CONSTRAINT "Roles_name_key51" UNIQUE (name),
    CONSTRAINT "Roles_name_key52" UNIQUE (name),
    CONSTRAINT "Roles_name_key53" UNIQUE (name),
    CONSTRAINT "Roles_name_key54" UNIQUE (name),
    CONSTRAINT "Roles_name_key6" UNIQUE (name),
    CONSTRAINT "Roles_name_key7" UNIQUE (name),
    CONSTRAINT "Roles_name_key8" UNIQUE (name),
    CONSTRAINT "Roles_name_key9" UNIQUE (name)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Roles"
    OWNER to postgres;
